# app-secrets.yml
apiVersion: v1
kind: Secret
metadata:
  name: app-postgres-secret
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: password
    secret-generator.v1.mittwald.de/encoding: base64url # to prevent slash in the secret from breaking DATABASE_URL
data: {}
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret-key-base
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: password
    secret-generator.v1.mittwald.de/length: "64" # for Elixir Phoenix's SECRET_KEY_BASE
data: {}
